spring:
  application:
    name: gateway-zuul

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      
#端口号  --server.port=8080
server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
    accept-count: 10000
    max-threads: 10000

logging:
  config: classpath:logback.xml

zuul:     
  host:
    max-per-route-connections: 10000
    max-total-connections: 10000
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000

  #路由  
  routes:
    baidu:
      path: /**
      stripPrefix: true
      url: https://www.baidu.com